// packages/react/src/chat-bubble.tsx
import { forwardRef } from 'react'
import { cn } from '@snuxt-ui/core'

export interface ChatBubbleProps extends React.HTMLAttributes<HTMLDivElement> {
  variant?: 'user' | 'ai'
}

export const ChatBubble = forwardRef<HTMLDivElement, ChatBubbleProps>(
  ({ variant = 'ai', className, ...props }, ref) => (
    <div ref={ref} className={cn('snx-chat-bubble', `snx-chat-bubble-${variant}`, className)} {...props} />
  )
)
ChatBubble.displayName = 'ChatBubble'

export interface ChatBubbleAvatarProps {
  src: string
  alt: string
  className?: string
}

export function ChatBubbleAvatar({ src, alt, className }: ChatBubbleAvatarProps) {
  return <img src={src} alt={alt} className={cn('snx-chat-bubble-avatar', className)} />
}

export const ChatBubbleContent = forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => (
    <div ref={ref} className={cn('snx-chat-bubble-content', className)} {...props} />
  )
)
ChatBubbleContent.displayName = 'ChatBubbleContent'

export const ChatBubbleTimestamp = forwardRef<HTMLSpanElement, React.HTMLAttributes<HTMLSpanElement>>(
  ({ className, ...props }, ref) => (
    <span ref={ref} className={cn('snx-chat-bubble-timestamp', className)} {...props} />
  )
)
ChatBubbleTimestamp.displayName = 'ChatBubbleTimestamp'

export function ChatBubbleTyping({ className }: { className?: string }) {
  return (
    <div className={cn('snx-chat-bubble-typing', className)}>
      <span className="snx-chat-bubble-typing-dot" />
      <span className="snx-chat-bubble-typing-dot" />
      <span className="snx-chat-bubble-typing-dot" />
    </div>
  )
}

// packages/angular/src/chat-bubble.component.ts
import { Component, input, computed } from '@angular/core'

type ChatBubbleVariant = 'user' | 'ai'

@Component({
  selector: 'snx-chat-bubble',
  standalone: true,
  template: `<div [class]="classes()"><ng-content /></div>`,
})
export class SnxChatBubbleComponent {
  variant = input<ChatBubbleVariant>('ai')
  class = input('')
  classes = computed(() =>
    ['snx-chat-bubble', `snx-chat-bubble-${this.variant()}`, this.class()].filter(Boolean).join(' ')
  )
}

@Component({
  selector: 'snx-chat-bubble-avatar',
  standalone: true,
  template: `<img class="snx-chat-bubble-avatar" [src]="src()" [alt]="alt()" />`,
})
export class SnxChatBubbleAvatarComponent {
  src = input.required<string>()
  alt = input('')
}

@Component({
  selector: 'snx-chat-bubble-content',
  standalone: true,
  template: `<div class="snx-chat-bubble-content"><ng-content /></div>`,
})
export class SnxChatBubbleContentComponent {}

@Component({
  selector: 'snx-chat-bubble-timestamp',
  standalone: true,
  template: `<span class="snx-chat-bubble-timestamp"><ng-content /></span>`,
})
export class SnxChatBubbleTimestampComponent {}

@Component({
  selector: 'snx-chat-bubble-typing',
  standalone: true,
  template: `
    <div class="snx-chat-bubble-typing">
      <span class="snx-chat-bubble-typing-dot"></span>
      <span class="snx-chat-bubble-typing-dot"></span>
      <span class="snx-chat-bubble-typing-dot"></span>
    </div>
  `,
})
export class SnxChatBubbleTypingComponent {}
