// packages/react/src/drawer.tsx
import { useEffect, useRef } from 'react'
import { cn, trapFocus, lockScroll } from '@snx-ui/core'
import { useDrawer } from './hooks/use-drawer'

export interface DrawerProps {
  open?: boolean
  onOpenChange?: (open: boolean) => void
  side?: 'left' | 'right' | 'top' | 'bottom'
  children: React.ReactNode
}

export function Drawer({ open: controlledOpen, onOpenChange, side = 'right', children }: DrawerProps) {
  const drawer = useDrawer({ side })
  const isOpen = controlledOpen ?? drawer.open
  const setOpen = onOpenChange ?? drawer.setOpen
  const contentRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    if (!isOpen) return
    const unlock = lockScroll()
    return unlock
  }, [isOpen])

  useEffect(() => {
    if (!isOpen || !contentRef.current) return
    const el = contentRef.current
    const handler = (e: KeyboardEvent) => {
      if (e.key === 'Escape') { setOpen(false); return }
      trapFocus(el, e)
    }
    el.addEventListener('keydown', handler)
    return () => el.removeEventListener('keydown', handler)
  }, [isOpen])

  if (!isOpen) return null

  return (
    <>
      <div className="snx-drawer-overlay" onClick={() => setOpen(false)} />
      <div
        ref={contentRef}
        className={cn('snx-drawer-content', `snx-drawer-content-${side}`)}
        role="dialog"
        aria-modal={true}
      >
        {children}
        <button className="snx-drawer-close" aria-label="Close" onClick={() => setOpen(false)} type="button">
          <svg xmlns="http://www.w3.org/2000/svg" width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <path d="M18 6 6 18" /><path d="m6 6 12 12" />
          </svg>
        </button>
      </div>
    </>
  )
}

export function DrawerHeader({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) {
  return <div className={cn('snx-drawer-header', className)} {...props} />
}
export function DrawerFooter({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) {
  return <div className={cn('snx-drawer-footer', className)} {...props} />
}
export function DrawerTitle({ className, ...props }: React.HTMLAttributes<HTMLHeadingElement>) {
  return <h2 className={cn('snx-drawer-title', className)} {...props} />
}
export function DrawerDescription({ className, ...props }: React.HTMLAttributes<HTMLParagraphElement>) {
  return <p className={cn('snx-drawer-description', className)} {...props} />
}
export function DrawerBody({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) {
  return <div className={cn('snx-drawer-body', className)} {...props} />
}

export { useDrawer } from './hooks/use-drawer'

// packages/angular/src/drawer.component.ts
import { Component, input, output, signal } from '@angular/core'

@Component({
  selector: 'snx-drawer',
  standalone: true,
  template: `
    @if (open()) {
      <div class="snx-drawer-overlay" (click)="close()"></div>
      <div
        [class]="'snx-drawer-content snx-drawer-content-' + side()"
        role="dialog"
        aria-modal="true"
        (keydown.escape)="close()"
      >
        <ng-content />
        <button class="snx-drawer-close" (click)="close()" aria-label="Close">
          <svg xmlns="http://www.w3.org/2000/svg" width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <path d="M18 6 6 18" /><path d="m6 6 12 12" />
          </svg>
        </button>
      </div>
    }
  `,
})
export class SnxDrawerComponent {
  side = input<'left' | 'right' | 'top' | 'bottom'>('right')
  open = signal(false)
  openChange = output<boolean>()

  show() { this.open.set(true); this.openChange.emit(true) }
  close() { this.open.set(false); this.openChange.emit(false) }
  toggle() { this.open.update(v => !v); this.openChange.emit(this.open()) }
}

@Component({ selector: 'snx-drawer-header', standalone: true, template: `<div class="snx-drawer-header"><ng-content /></div>` })
export class SnxDrawerHeaderComponent {}

@Component({ selector: 'snx-drawer-footer', standalone: true, template: `<div class="snx-drawer-footer"><ng-content /></div>` })
export class SnxDrawerFooterComponent {}

@Component({ selector: 'snx-drawer-title', standalone: true, template: `<h2 class="snx-drawer-title"><ng-content /></h2>` })
export class SnxDrawerTitleComponent {}

@Component({ selector: 'snx-drawer-description', standalone: true, template: `<p class="snx-drawer-description"><ng-content /></p>` })
export class SnxDrawerDescriptionComponent {}

@Component({ selector: 'snx-drawer-body', standalone: true, template: `<div class="snx-drawer-body"><ng-content /></div>` })
export class SnxDrawerBodyComponent {}
