// packages/react/src/progress.tsx
import { forwardRef } from 'react'
import { cn } from '@snx-ui/core'

export interface ProgressProps extends React.HTMLAttributes<HTMLDivElement> {
  value?: number
  max?: number
}

export const Progress = forwardRef<HTMLDivElement, ProgressProps>(
  ({ value = 0, max = 100, className, ...props }, ref) => {
    const percentage = Math.min(Math.max((value / max) * 100, 0), 100)
    return (
      <div
        ref={ref}
        role="progressbar"
        aria-valuenow={value}
        aria-valuemin={0}
        aria-valuemax={max}
        className={cn('snx-progress', className)}
        {...props}
      >
        <div
          className="snx-progress-indicator"
          style={{ transform: `translateX(-${100 - percentage}%)` }}
        />
      </div>
    )
  }
)
Progress.displayName = 'Progress'

// packages/angular/src/progress.component.ts
import { Component, input, computed } from '@angular/core'

@Component({
  selector: 'snx-progress',
  standalone: true,
  template: `
    <div class="snx-progress" role="progressbar"
         [attr.aria-valuenow]="value()" [attr.aria-valuemin]="0" [attr.aria-valuemax]="max()">
      <div class="snx-progress-indicator" [style.transform]="transform()"></div>
    </div>
  `,
})
export class SnxProgressComponent {
  value = input(0)
  max = input(100)
  transform = computed(() => {
    const pct = Math.min(Math.max((this.value() / this.max()) * 100, 0), 100)
    return `translateX(-${100 - pct}%)`
  })
}
