// packages/react/src/select.tsx
import { useRef, useEffect } from 'react'
import { cn, createClickOutsideHandler } from '@snuxt-ui/core'
import { useSelect } from './hooks/use-select'
import type { SelectOption } from '@snuxt-ui/core'

export interface SelectProps {
  options: SelectOption[]
  placeholder?: string
  className?: string
  onChange?: (value: string) => void
}

export function Select({ options, placeholder = 'Select...', className, onChange }: SelectProps) {
  const select = useSelect(options)
  const containerRef = useRef<HTMLDivElement>(null)

  const selectedLabel = options.find(o => o.value === select.selectedValue)?.label

  useEffect(() => {
    if (!select.isOpen || !containerRef.current) return
    return createClickOutsideHandler(containerRef.current, () => select.setIsOpen(false))
  }, [select.isOpen])

  useEffect(() => {
    if (select.selectedValue && onChange) {
      onChange(select.selectedValue)
    }
  }, [select.selectedValue])

  return (
    <div ref={containerRef} className={cn('relative', className)}>
      <button
        className="snx-select-trigger"
        aria-expanded={select.isOpen}
        aria-haspopup="listbox"
        aria-activedescendant={select.isOpen && select.highlightedIndex >= 0 ? `select-option-${options[select.highlightedIndex]?.value}` : undefined}
        onClick={() => select.setIsOpen(!select.isOpen)}
        onKeyDown={select.handleKeyDown}
        type="button"
      >
        <span className={cn(!selectedLabel && 'text-muted-foreground')}>
          {selectedLabel || placeholder}
        </span>
        <svg
          className={cn('h-4 w-4 opacity-50 transition-transform', select.isOpen && 'rotate-180')}
          xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none"
          stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"
        >
          <path d="m6 9 6 6 6-6" />
        </svg>
      </button>
      {select.isOpen && (
        <div className="snx-select-content absolute top-full mt-1 w-full">
          <div className="snx-select-viewport" role="listbox">
            {options.map((option, index) => (
              <div
                key={option.value}
                role="option"
                aria-selected={option.value === select.selectedValue}
                aria-disabled={option.disabled || undefined}
                className={cn(
                  'snx-select-item',
                  index === select.highlightedIndex && !option.disabled && 'snx-select-item-active',
                  option.value === select.selectedValue && 'snx-select-item-selected',
                  option.disabled && 'opacity-50 pointer-events-none'
                )}
                onClick={() => {
                  if (!option.disabled) {
                    select.setSelectedValue(option.value)
                    select.setIsOpen(false)
                  }
                }}
                onMouseEnter={() => {
                  if (!option.disabled) select.setHighlightedIndex(index)
                }}
              >
                {option.value === select.selectedValue && (
                  <svg className="absolute right-2 h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <path d="M20 6 9 17l-5-5" />
                  </svg>
                )}
                {option.label}
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  )
}

export { useSelect } from './hooks/use-select'

// packages/angular/src/select.component.ts
import { Component, input, output, signal, computed, ElementRef, viewChild, HostListener } from '@angular/core'
import { createSelect, type SelectOption } from '@snuxt-ui/core'

@Component({
  selector: 'snx-select',
  standalone: true,
  template: `
    <div class="relative" #container>
      <button
        class="snx-select-trigger"
        [attr.aria-expanded]="isOpen()"
        aria-haspopup="listbox"
        (click)="toggle()"
        (keydown)="onKeyDown($event)"
      >
        <span>{{ selectedLabel() || placeholder() }}</span>
        <svg class="h-4 w-4 opacity-50" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <path d="m6 9 6 6 6-6" />
        </svg>
      </button>
      @if (isOpen()) {
        <div class="snx-select-content absolute top-full mt-1 w-full">
          <div class="snx-select-viewport" role="listbox">
            @for (option of options(); track option.value; let i = $index) {
              <div
                role="option"
                [attr.aria-selected]="option.value === selectedValue()"
                [attr.aria-disabled]="option.disabled"
                [class]="getItemClasses(option, i)"
                (click)="selectOption(option)"
                (mouseenter)="highlightedIndex.set(i)"
              >
                {{ option.label }}
              </div>
            }
          </div>
        </div>
      }
    </div>
  `,
  host: {
    '(document:click)': 'onDocumentClick($event)',
  },
})
export class SnxSelectComponent {
  options = input<SelectOption[]>([])
  placeholder = input('Select...')
  valueChange = output<string>()

  isOpen = signal(false)
  selectedValue = signal<string | null>(null)
  highlightedIndex = signal(0)

  container = viewChild<ElementRef>('container')

  selectedLabel = computed(() => {
    const val = this.selectedValue()
    return this.options().find(o => o.value === val)?.label ?? ''
  })

  toggle() { this.isOpen.update(v => !v) }

  selectOption(option: SelectOption) {
    if (option.disabled) return
    this.selectedValue.set(option.value)
    this.valueChange.emit(option.value)
    this.isOpen.set(false)
  }

  getItemClasses(option: SelectOption, index: number): string {
    return [
      'snx-select-item',
      index === this.highlightedIndex() ? 'snx-select-item-active' : '',
      option.value === this.selectedValue() ? 'snx-select-item-selected' : '',
    ].filter(Boolean).join(' ')
  }

  onKeyDown(event: KeyboardEvent) {
    const opts = this.options().filter(o => !o.disabled)
    if (event.key === 'ArrowDown') {
      event.preventDefault()
      if (!this.isOpen()) { this.isOpen.set(true); return }
      this.highlightedIndex.update(i => (i + 1) % opts.length)
    } else if (event.key === 'ArrowUp') {
      event.preventDefault()
      this.highlightedIndex.update(i => (i - 1 + opts.length) % opts.length)
    } else if (event.key === 'Enter' || event.key === ' ') {
      event.preventDefault()
      if (this.isOpen()) {
        const opt = opts[this.highlightedIndex()]
        if (opt) this.selectOption(opt)
      } else {
        this.isOpen.set(true)
      }
    } else if (event.key === 'Escape') {
      this.isOpen.set(false)
    }
  }

  onDocumentClick(event: MouseEvent) {
    const el = this.container()?.nativeElement
    if (el && !el.contains(event.target as Node)) {
      this.isOpen.set(false)
    }
  }
}
