// packages/react/src/separator.tsx
import { forwardRef } from 'react'
import { cn } from '@snx-ui/core'

export interface SeparatorProps extends React.HTMLAttributes<HTMLDivElement> {
  orientation?: 'horizontal' | 'vertical'
}

export const Separator = forwardRef<HTMLDivElement, SeparatorProps>(
  ({ orientation = 'horizontal', className, ...props }, ref) => (
    <div
      ref={ref}
      role="separator"
      aria-orientation={orientation}
      className={cn('snx-separator', `snx-separator-${orientation}`, className)}
      {...props}
    />
  )
)
Separator.displayName = 'Separator'

// packages/angular/src/separator.component.ts
import { Component, input, computed } from '@angular/core'

@Component({
  selector: 'snx-separator',
  standalone: true,
  template: `<div [class]="classes()" role="separator" [attr.aria-orientation]="orientation()"></div>`,
})
export class SnxSeparatorComponent {
  orientation = input<'horizontal' | 'vertical'>('horizontal')
  class = input('')

  classes = computed(() =>
    ['snx-separator', `snx-separator-${this.orientation()}`, this.class()].filter(Boolean).join(' ')
  )
}
