// packages/react/src/source-card.tsx
import { forwardRef } from 'react'
import { cn } from '@snuxt-ui/core'

export interface SourceCardsProps extends React.HTMLAttributes<HTMLDivElement> {}

export const SourceCards = forwardRef<HTMLDivElement, SourceCardsProps>(
  ({ className, ...props }, ref) => (
    <div ref={ref} className={cn('snx-source-cards', className)} {...props} />
  )
)
SourceCards.displayName = 'SourceCards'

export interface SourceCardProps extends React.AnchorHTMLAttributes<HTMLAnchorElement> {
  favicon?: string
  title: string
  domain: string
  index?: number
}

export const SourceCard = forwardRef<HTMLAnchorElement, SourceCardProps>(
  ({ favicon, title, domain, index, className, ...props }, ref) => (
    <a
      ref={ref}
      className={cn('snx-source-card', className)}
      target="_blank"
      rel="noopener noreferrer"
      {...props}
    >
      {favicon && <img className="snx-source-card-favicon" src={favicon} alt={domain} />}
      <div className="snx-source-card-body">
        <p className="snx-source-card-title">{title}</p>
        <p className="snx-source-card-domain">{domain}</p>
      </div>
      {index != null && <span className="snx-source-card-index">{index}</span>}
    </a>
  )
)
SourceCard.displayName = 'SourceCard'

// packages/angular/src/source-card.component.ts
import { Component, input } from '@angular/core'

@Component({
  selector: 'snx-source-cards',
  standalone: true,
  template: `<div class="snx-source-cards"><ng-content /></div>`,
})
export class SnxSourceCardsComponent {}

@Component({
  selector: 'snx-source-card',
  standalone: true,
  template: `
    <a [href]="href()" class="snx-source-card" target="_blank" rel="noopener noreferrer">
      @if (favicon()) {
        <img class="snx-source-card-favicon" [src]="favicon()" [alt]="domain()" />
      }
      <div class="snx-source-card-body">
        <p class="snx-source-card-title">{{ title() }}</p>
        <p class="snx-source-card-domain">{{ domain() }}</p>
      </div>
      @if (index()) {
        <span class="snx-source-card-index">{{ index() }}</span>
      }
    </a>
  `,
})
export class SnxSourceCardComponent {
  href = input.required<string>()
  favicon = input('')
  title = input('')
  domain = input('')
  index = input<number | undefined>(undefined)
}
