// packages/react/src/toast.tsx
import { cn } from '@snx-ui/core'
import { useToast } from './hooks/use-toast'

export interface ToasterProps {
  position?: 'top-right' | 'top-left' | 'bottom-right' | 'bottom-left'
  className?: string
}

export function Toaster({ position = 'bottom-right', className }: ToasterProps) {
  const { toasts, dismiss } = useToast()

  return (
    <div className={cn('snx-toaster', `snx-toaster-${position}`, className)}>
      {toasts.map((t) => (
        <div
          key={t.id}
          className={cn(
            'snx-toast group',
            t.variant === 'destructive' && 'snx-toast-destructive',
            t.variant === 'success' && 'snx-toast-success'
          )}
        >
          <div className="flex-1">
            {t.title && <div className="snx-toast-title">{t.title}</div>}
            {t.description && <div className="snx-toast-description">{t.description}</div>}
          </div>
          {t.action && (
            <button className="snx-toast-action" onClick={t.action.onClick} type="button">
              {t.action.label}
            </button>
          )}
          <button
            className="snx-toast-close"
            onClick={() => dismiss(t.id)}
            type="button"
            aria-label="Close"
          >
            <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <path d="M18 6 6 18" /><path d="m6 6 12 12" />
            </svg>
          </button>
        </div>
      ))}
    </div>
  )
}

export { useToast } from './hooks/use-toast'

// packages/angular/src/toast.component.ts
import { Component, Injectable, signal } from '@angular/core'

export interface ToastData {
  id: string
  title?: string
  description?: string
  variant?: 'default' | 'destructive' | 'success'
}

@Injectable({ providedIn: 'root' })
export class SnxToastService {
  toasts = signal<ToastData[]>([])
  private counter = 0

  show(toast: Omit<ToastData, 'id'>, duration = 5000): string {
    const id = `toast-${++this.counter}`
    this.toasts.update(t => [...t, { id, ...toast }])
    if (duration > 0) {
      setTimeout(() => this.dismiss(id), duration)
    }
    return id
  }

  success(title: string, description?: string) {
    return this.show({ title, description, variant: 'success' })
  }

  error(title: string, description?: string) {
    return this.show({ title, description, variant: 'destructive' })
  }

  dismiss(id: string) {
    this.toasts.update(t => t.filter(x => x.id !== id))
  }
}

@Component({
  selector: 'snx-toaster',
  standalone: true,
  template: `
    <div class="snx-toaster snx-toaster-bottom-right">
      @for (t of toastService.toasts(); track t.id) {
        <div
          [class]="'snx-toast group' + (t.variant === 'destructive' ? ' snx-toast-destructive' : '') + (t.variant === 'success' ? ' snx-toast-success' : '')"
        >
          <div class="flex-1">
            @if (t.title) { <div class="snx-toast-title">{{ t.title }}</div> }
            @if (t.description) { <div class="snx-toast-description">{{ t.description }}</div> }
          </div>
          <button class="snx-toast-close" (click)="toastService.dismiss(t.id)" aria-label="Close">
            <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
              <path d="M18 6 6 18" /><path d="m6 6 12 12" />
            </svg>
          </button>
        </div>
      }
    </div>
  `,
})
export class SnxToasterComponent {
  constructor(public toastService: SnxToastService) {}
}
