// packages/angular/src/alert.component.ts
import { Component, input, computed } from '@angular/core'

@Component({
  selector: 'snx-alert',
  standalone: true,
  template: `<div [class]="classes()" role="alert"><ng-content /></div>`,
})
export class SnxAlertComponent {
  variant = input<'default' | 'destructive' | 'success' | 'warning'>('default')
  classes = computed(() => `snx-alert snx-alert-${this.variant()}`)
}

@Component({
  selector: 'snx-alert-title',
  standalone: true,
  template: `<h5 class="snx-alert-title"><ng-content /></h5>`,
})
export class SnxAlertTitleComponent {}

@Component({
  selector: 'snx-alert-description',
  standalone: true,
  template: `<div class="snx-alert-description"><ng-content /></div>`,
})
export class SnxAlertDescriptionComponent {}

// packages/react/src/alert.tsx
import { forwardRef } from 'react'
import { cn } from '@snx-ui/core'

export interface AlertProps extends React.HTMLAttributes<HTMLDivElement> {
  variant?: 'default' | 'destructive' | 'success' | 'warning'
}

export const Alert = forwardRef<HTMLDivElement, AlertProps>(
  ({ variant = 'default', className, ...props }, ref) => (
    <div
      ref={ref}
      role="alert"
      className={cn('snx-alert', `snx-alert-${variant}`, className)}
      {...props}
    />
  )
)
Alert.displayName = 'Alert'

export function AlertTitle({ className, ...props }: React.HTMLAttributes<HTMLHeadingElement>) {
  return <h5 className={cn('snx-alert-title', className)} {...props} />
}

export function AlertDescription({ className, ...props }: React.HTMLAttributes<HTMLParagraphElement>) {
  return <div className={cn('snx-alert-description', className)} {...props} />
}
