// packages/angular/src/button.component.ts
import { Component, computed, input } from '@angular/core'

type ButtonVariant = 'primary' | 'secondary' | 'outline' | 'ghost' | 'destructive' | 'link'
type ButtonSize = 'sm' | 'md' | 'lg' | 'icon'

@Component({
  selector: 'snx-button',
  standalone: true,
  template: `
    <button [class]="classes()" [disabled]="disabled()" [type]="type()">
      <ng-content />
    </button>
  `,
})
export class SnxButtonComponent {
  variant = input<ButtonVariant>('primary')
  size = input<ButtonSize>('md')
  disabled = input(false)
  type = input<'button' | 'submit' | 'reset'>('button')
  class = input('')

  classes = computed(() =>
    ['snx-btn', `snx-btn-${this.variant()}`, `snx-btn-${this.size()}`, this.class()]
      .filter(Boolean)
      .join(' ')
  )
}

// packages/react/src/button.tsx
import { forwardRef } from 'react'
import { cn } from '@snx-ui/core'

export interface ButtonProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: 'primary' | 'secondary' | 'outline' | 'ghost' | 'destructive' | 'link'
  size?: 'sm' | 'md' | 'lg' | 'icon'
}

export const Button = forwardRef<HTMLButtonElement, ButtonProps>(
  ({ variant = 'primary', size = 'md', className, ...props }, ref) => (
    <button
      ref={ref}
      className={cn('snx-btn', `snx-btn-${variant}`, `snx-btn-${size}`, className)}
      {...props}
    />
  )
)
Button.displayName = 'Button'
