// packages/angular/src/dropdown-menu.component.ts
import { Component, input, signal, ElementRef, viewChild } from '@angular/core'

export interface DropdownItem {
  id: string
  label: string
  disabled?: boolean
  type?: 'item' | 'separator' | 'label'
  shortcut?: string
}

@Component({
  selector: 'snx-dropdown-menu',
  standalone: true,
  template: `
    <div class="relative inline-block" #container>
      <div (click)="toggle()">
        <ng-content select="[trigger]" />
      </div>
      @if (isOpen()) {
        <div class="snx-dropdown-menu-content absolute top-full mt-1 right-0" role="menu">
          @for (item of items(); track item.id) {
            @if (item.type === 'separator') {
              <div class="snx-dropdown-menu-separator" role="separator"></div>
            } @else if (item.type === 'label') {
              <div class="snx-dropdown-menu-label">{{ item.label }}</div>
            } @else {
              <div
                role="menuitem"
                [class]="'snx-dropdown-menu-item' + (item.disabled ? ' opacity-50 pointer-events-none' : '')"
                (click)="selectItem(item)"
                [attr.aria-disabled]="item.disabled"
              >
                <span class="flex-1">{{ item.label }}</span>
                @if (item.shortcut) {
                  <span class="snx-dropdown-menu-shortcut">{{ item.shortcut }}</span>
                }
              </div>
            }
          }
        </div>
      }
    </div>
  `,
  host: { '(document:click)': 'onDocumentClick($event)' },
})
export class SnxDropdownMenuComponent {
  items = input<DropdownItem[]>([])
  isOpen = signal(false)
  container = viewChild<ElementRef>('container')

  toggle() { this.isOpen.update(v => !v) }
  close() { this.isOpen.set(false) }

  selectItem(item: DropdownItem) {
    if (!item.disabled) this.isOpen.set(false)
  }

  onDocumentClick(event: MouseEvent) {
    const el = this.container()?.nativeElement
    if (el && !el.contains(event.target as Node)) this.isOpen.set(false)
  }
}

// packages/react/src/dropdown-menu.tsx
import { useRef, useEffect } from 'react'
import { cn, createClickOutsideHandler } from '@snx-ui/core'
import { useDropdownMenu } from './hooks/use-dropdown-menu'
import type { DropdownMenuItem } from '@snx-ui/core'

export interface DropdownMenuProps {
  trigger: React.ReactNode
  items: DropdownMenuItem[]
  className?: string
  align?: 'start' | 'end'
}

export function DropdownMenu({ trigger, items, className, align = 'end' }: DropdownMenuProps) {
  const menu = useDropdownMenu(items)
  const containerRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    if (!menu.isOpen || !containerRef.current) return
    return createClickOutsideHandler(containerRef.current, () => menu.setIsOpen(false))
  }, [menu.isOpen])

  const actionItems = items.filter(i => i.type !== 'separator' && i.type !== 'label' && !i.disabled)

  return (
    <div ref={containerRef} className="relative inline-block" onKeyDown={menu.handleKeyDown}>
      <div
        onClick={() => menu.setIsOpen(!menu.isOpen)}
        aria-haspopup="menu"
        aria-expanded={menu.isOpen}
      >
        {trigger}
      </div>
      {menu.isOpen && (
        <div
          className={cn(
            'snx-dropdown-menu-content absolute top-full mt-1',
            align === 'end' ? 'right-0' : 'left-0',
            className
          )}
          role="menu"
        >
          {items.map((item) => {
            if (item.type === 'separator') {
              return <div key={item.id} className="snx-dropdown-menu-separator" role="separator" />
            }
            if (item.type === 'label') {
              return <div key={item.id} className="snx-dropdown-menu-label">{item.label}</div>
            }
            const actionIndex = actionItems.findIndex(ai => ai.id === item.id)
            return (
              <div
                key={item.id}
                role="menuitem"
                aria-disabled={item.disabled || undefined}
                className={cn(
                  'snx-dropdown-menu-item',
                  actionIndex === menu.highlightedIndex && !item.disabled && 'snx-dropdown-menu-item-active',
                  item.disabled && 'opacity-50 pointer-events-none'
                )}
                onClick={() => {
                  if (!item.disabled) {
                    item.onSelect?.()
                    menu.setIsOpen(false)
                  }
                }}
                onMouseEnter={() => {
                  if (!item.disabled) menu.setHighlightedIndex(actionIndex)
                }}
              >
                <span className="flex-1">{item.label}</span>
                {item.shortcut && (
                  <span className="snx-dropdown-menu-shortcut">{item.shortcut}</span>
                )}
              </div>
            )
          })}
        </div>
      )}
    </div>
  )
}

export { useDropdownMenu } from './hooks/use-dropdown-menu'
