// packages/angular/src/popover.component.ts
import { Component, input, signal, ElementRef, viewChild } from '@angular/core'

@Component({
  selector: 'snx-popover',
  standalone: true,
  template: `
    <div class="relative inline-block" #container>
      <div (click)="toggle()">
        <ng-content select="[trigger]" />
      </div>
      @if (isOpen()) {
        <div
          class="snx-popover-content absolute top-full mt-2"
          role="dialog"
          (keydown.escape)="close()"
        >
          <ng-content />
        </div>
      }
    </div>
  `,
  host: {
    '(document:click)': 'onDocumentClick($event)',
  },
})
export class SnxPopoverComponent {
  isOpen = signal(false)
  container = viewChild<ElementRef>('container')

  toggle() { this.isOpen.update(v => !v) }
  close() { this.isOpen.set(false) }
  show() { this.isOpen.set(true) }

  onDocumentClick(event: MouseEvent) {
    const el = this.container()?.nativeElement
    if (el && !el.contains(event.target as Node)) {
      this.isOpen.set(false)
    }
  }
}

// packages/react/src/popover.tsx
import { useRef, useEffect } from 'react'
import { cn, createClickOutsideHandler } from '@snx-ui/core'
import { usePopover } from './hooks/use-popover'

export interface PopoverProps {
  trigger: React.ReactNode
  children: React.ReactNode
  className?: string
}

export function Popover({ trigger, children, className }: PopoverProps) {
  const popover = usePopover()
  const containerRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    if (!popover.open || !containerRef.current) return
    return createClickOutsideHandler(containerRef.current, () => popover.setOpen(false))
  }, [popover.open])

  return (
    <div ref={containerRef} className="relative inline-block">
      <div onClick={() => popover.setOpen(!popover.open)}>{trigger}</div>
      {popover.open && (
        <div
          className={cn('snx-popover-content absolute top-full mt-2', className)}
          role="dialog"
          onKeyDown={(e) => { if (e.key === 'Escape') popover.setOpen(false) }}
        >
          {children}
        </div>
      )}
    </div>
  )
}

export { usePopover } from './hooks/use-popover'
