// packages/angular/src/streaming-text.component.ts
import { Component } from '@angular/core'

@Component({
  selector: 'snx-streaming-text',
  standalone: true,
  template: `<div class="snx-streaming-text-cursor"><ng-content /></div>`,
})
export class SnxStreamingTextComponent {}

@Component({
  selector: 'snx-streaming-text-fade-in',
  standalone: true,
  template: `<span class="snx-streaming-text-fade-in"><ng-content /></span>`,
})
export class SnxStreamingTextFadeInComponent {}

@Component({
  selector: 'snx-streaming-text-word',
  standalone: true,
  template: `<span class="snx-streaming-text-word"><ng-content /></span>`,
})
export class SnxStreamingTextWordComponent {}

@Component({
  selector: 'snx-streaming-text-line',
  standalone: true,
  template: `<div class="snx-streaming-text-line"><ng-content /></div>`,
})
export class SnxStreamingTextLineComponent {}

@Component({
  selector: 'snx-streaming-text-skeleton',
  standalone: true,
  template: `<div class="snx-streaming-text-skeleton"><ng-content /></div>`,
})
export class SnxStreamingTextSkeletonComponent {}

@Component({
  selector: 'snx-streaming-text-skeleton-line',
  standalone: true,
  template: `<div class="snx-streaming-text-skeleton-line"></div>`,
})
export class SnxStreamingTextSkeletonLineComponent {}

// packages/react/src/streaming-text.tsx
import { forwardRef } from 'react'
import { cn } from '@snuxt-ui/core'

export interface StreamingTextProps extends React.HTMLAttributes<HTMLDivElement> {}

export const StreamingText = forwardRef<HTMLDivElement, StreamingTextProps>(
  ({ className, ...props }, ref) => (
    <div ref={ref} className={cn('snx-streaming-text-cursor', className)} {...props} />
  )
)
StreamingText.displayName = 'StreamingText'

export const StreamingTextFadeIn = forwardRef<HTMLSpanElement, React.HTMLAttributes<HTMLSpanElement>>(
  ({ className, ...props }, ref) => (
    <span ref={ref} className={cn('snx-streaming-text-fade-in', className)} {...props} />
  )
)
StreamingTextFadeIn.displayName = 'StreamingTextFadeIn'

export const StreamingTextWord = forwardRef<HTMLSpanElement, React.HTMLAttributes<HTMLSpanElement>>(
  ({ className, ...props }, ref) => (
    <span ref={ref} className={cn('snx-streaming-text-word', className)} {...props} />
  )
)
StreamingTextWord.displayName = 'StreamingTextWord'

export const StreamingTextLine = forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => (
    <div ref={ref} className={cn('snx-streaming-text-line', className)} {...props} />
  )
)
StreamingTextLine.displayName = 'StreamingTextLine'

export const StreamingTextSkeleton = forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => (
    <div ref={ref} className={cn('snx-streaming-text-skeleton', className)} {...props} />
  )
)
StreamingTextSkeleton.displayName = 'StreamingTextSkeleton'

export const StreamingTextSkeletonLine = forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => (
    <div ref={ref} className={cn('snx-streaming-text-skeleton-line', className)} {...props} />
  )
)
StreamingTextSkeletonLine.displayName = 'StreamingTextSkeletonLine'
