// packages/angular/src/suggestion-chips.component.ts
import { Component, input, computed } from '@angular/core'

type SuggestionChipVariant = 'default' | 'primary' | 'outline'

@Component({
  selector: 'snx-suggestion-chips',
  standalone: true,
  template: `<div class="snx-suggestion-chips"><ng-content /></div>`,
})
export class SnxSuggestionChipsComponent {}

@Component({
  selector: 'snx-suggestion-chip',
  standalone: true,
  template: `<button [class]="classes()" type="button"><ng-content /></button>`,
})
export class SnxSuggestionChipComponent {
  variant = input<SuggestionChipVariant>('default')
  class = input('')
  classes = computed(() =>
    ['snx-suggestion-chip', `snx-suggestion-chip-${this.variant()}`, this.class()].filter(Boolean).join(' ')
  )
}

// packages/react/src/suggestion-chips.tsx
import { forwardRef } from 'react'
import { cn } from '@snuxt-ui/core'

export interface SuggestionChipsProps extends React.HTMLAttributes<HTMLDivElement> {}

export const SuggestionChips = forwardRef<HTMLDivElement, SuggestionChipsProps>(
  ({ className, ...props }, ref) => (
    <div ref={ref} className={cn('snx-suggestion-chips', className)} {...props} />
  )
)
SuggestionChips.displayName = 'SuggestionChips'

export interface SuggestionChipProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: 'default' | 'primary' | 'outline'
}

export const SuggestionChip = forwardRef<HTMLButtonElement, SuggestionChipProps>(
  ({ variant = 'default', className, ...props }, ref) => (
    <button
      ref={ref}
      type="button"
      className={cn('snx-suggestion-chip', `snx-suggestion-chip-${variant}`, className)}
      {...props}
    />
  )
)
SuggestionChip.displayName = 'SuggestionChip'
