// packages/angular/src/switch.component.ts
import { Component, input, output, signal, computed } from '@angular/core'

@Component({
  selector: 'snx-switch',
  standalone: true,
  template: `
    <button
      type="button"
      role="switch"
      [attr.aria-checked]="checked()"
      [attr.aria-disabled]="disabled()"
      [disabled]="disabled()"
      [class]="'snx-switch'"
      (click)="toggle()"
      (keydown.space)="$event.preventDefault(); toggle()"
      (keydown.enter)="$event.preventDefault(); toggle()"
    >
      <span class="snx-switch-thumb"></span>
    </button>
  `,
})
export class SnxSwitchComponent {
  checked = signal(false)
  disabled = input(false)
  checkedChange = output<boolean>()

  toggle() {
    if (this.disabled()) return
    this.checked.update(v => !v)
    this.checkedChange.emit(this.checked())
  }
}

// packages/react/src/switch.tsx
import { forwardRef } from 'react'
import { cn } from '@snx-ui/core'

export interface SwitchProps {
  checked?: boolean
  onCheckedChange?: (checked: boolean) => void
  disabled?: boolean
  className?: string
  id?: string
  name?: string
}

export const Switch = forwardRef<HTMLButtonElement, SwitchProps>(
  ({ checked = false, onCheckedChange, disabled, className, id, name }, ref) => (
    <button
      ref={ref}
      type="button"
      role="switch"
      id={id}
      aria-checked={checked}
      aria-disabled={disabled || undefined}
      disabled={disabled}
      className={cn('snx-switch', className)}
      onClick={() => onCheckedChange?.(!checked)}
      onKeyDown={(e) => {
        if (e.key === ' ' || e.key === 'Enter') {
          e.preventDefault()
          onCheckedChange?.(!checked)
        }
      }}
    >
      <span className="snx-switch-thumb" />
      {name && <input type="hidden" name={name} value={checked ? 'on' : 'off'} />}
    </button>
  )
)
Switch.displayName = 'Switch'
